In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('./diabetes_latih.csv')

X_train = df.values
X_train = np.delete(X_train,8,axis=1)

y_train = df['Outcome'].values

df = pd.read_csv('./diabetes_uji.csv')

X_test = df.values
X_test = np.delete(X_test,8,axis=1)

y_test = df['Outcome'].values

In [25]:
from sklearn.preprocessing import MinMaxScaler

X_train = MinMaxScaler().fit_transform(X_train)
X_test = MinMaxScaler().fit_transform(X_test)

print(X_train)

[[0.47058824 0.94472362 0.68421053 ... 0.71385991 0.02519214 0.36666667]
 [0.41176471 0.7638191  0.77192982 ... 0.74515648 0.11058924 0.25      ]
 [0.11764706 0.49748744 0.45614035 ... 0.36661699 0.23868488 0.        ]
 ...
 [0.29411765 0.6080402  0.63157895 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.52631579 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.61403509 ... 0.45305514 0.10119556 0.03333333]]


In [ ]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(hidden_layer_sizes=3,learning_rate_init=0.1,max_iter=100)

clf.fit(X_train, y_train)

In [ ]:
y_pred = clf.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score

round(accuracy_score(y_test,y_pred),3)

0.76

In [ ]:
df.info()

In [27]:
import pickle

with open('NND_pickle','wb') as r:
    pickle.dump(clf,r)

In [28]:
with open('NND_pickle','rb') as r:
    nndp = pickle.load(r)

In [29]:
from sklearn.metrics import accuracy_score

y_pred = nndp.predict(X_test)
round(accuracy_score(y_test,y_pred),3)

0.76

In [30]:
print(y_pred)

[1 0 1 0 1 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 1 0 1 1 0 0 1 0 1
 1 0 1 1 1 0 1 1 1 1 0 0 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1
 1 0 0 1 1 1 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1
 1 0 0 0 1 1]
